version: '3.8'

services:
  metabase:
    build: .
    container_name: metabase
    ports:
      - "3000:3000"
    networks:
      - petalSync_network

networks:
  petalSync_network:
    external: true
